// elastic adaptive
export const SET_CURRENT_FONT_SIZE = 'SET_CURRENT_FONT_SIZE'
export const SET_USER_DEVICE_TYPE = 'SET_USER_DEVICE_TYPE'

// ui
export const SET_LANG = 'SET_LANG'
export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const SET_THEME = 'SET_THEME'
export const SET_BUTTON_TYPE = 'SET_BUTTON_TYPE'

// data
export const SET_LOADING_STATE = 'SET_LOADING_STATE'
export const CONNECT_WALLET = 'CONNECT_WALLET'
export const GET_WALLET_BALANCE = 'GET_WALLET_BALANCE'
export const GET_AVAILABLE_TOKENS = 'GET_AVAILABLE_TOKENS'
export const GET_EXCHANGE_ESTIMATE = 'GET_EXCHANGE_ESTIMATE'
export const CREATE_WEB3_INSTANCE = 'CREATE_WEB3_INSTANCE'
export const SAVE_SWAP_DATA = 'SAVE_SWAP_DATA'
export const SAVE_TX_DATA = 'SAVE_TX_DATA'
export const RESET_DATA = 'RESET_DATA'
export const GET_ALLOWANCE = 'GET_ALLOWANCE'
export const CLEAR_ALLOWANCE = 'CLEAR_ALLOWANCE'
export const GET_SYSTEM_GAS = 'GET_SYSTEM_GAS'
export const SET_GAS_FEE = 'SET_GAS_FEE'
export const SET_GAS_FEE_OPTIONS = 'SET_GAS_FEE_OPTIONS'
export const SET_PRICE_SLIPPAGE = 'SET_PRICE_SLIPPAGE'
export const SAVE_TOKENS_RATING = 'SAVE_TOKENS_RATING'
